[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "semver"
description = "Annotation protocol to allow very thorough isinstance checks."
readme = "README.md"
requires-python = ">=3.10"
maintainers = [
    { name = "Steffen Burgers", email = "steffen.burgers@rhdhv.com" },
    { name = "Ruud Kassing", email = "ruud.kassing@rhdhv.com" },
    { name = "Miguel Pereira Hernandez", email = "miguel.hernandez@rhdhv.com" },
    { name = "Jesse de Ruijter", email = "jesse.de.ruijter@rhdhv.com" },
    { name = "Pierpaolo Lucarelli", email = "pierpaolo.lucarelli@rhdhv.com" }
]
dependencies = []
optional-dependencies.dev = ["pytest", "black", "pre-commit", "isort", "bandit==1.7.0", "flake8"]
dynamic = ["version"]

[tool.setuptools]
packages.find.include = ["semversion*"]
dynamic.version.attr = "semversion._version.__version__"

[tool.black]
line-length = 99

[tool.ruff]
target-version = "py310"
line-length = 99

[tool.ruff.mccabe]
max-complexity = 10

[tool.ruff.per-file-ignores]
"tests/*" = ["D102", "PLR2004", "S101"]
"semversion/patterns.py" = ["E501"]

[tool.pytest.ini_options]
filterwarnings = [
    "ignore",
    "default:::semversion.*",
]
